### ISSUE TITLE
hsail-gdb incompatible with HSA_ENABLE_INTERRUPT=0

### ISSUE THREAD

**Issue by harald-lang** [HSAFoundation/HSA-Debugger-AMD#1]
`hsail-gdb` terminates with the following error when HSA_ENABLE_INTERRUPT is set to 0.

`AgentContext.cpp:145: HsailAgentStatus HwDbgAgent::AgentContext::BeginDebugging(): Assertion `dbeStatus == HWDBG_STATUS_SUCCESS' failed.`

**Comment by bpurnomo** [comment]
Thanks, we will take a look.
